/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kttpd

import java.io.File
import java.io.ObjectInputStream
import java.io.ObjectOutputStream
import java.io.Serializable
import kotlin.test.assertEquals


data class Person(
    val name: String = "John Doe",
    val age: Int = 42,
) : Serializable

fun main() {
    val person = Person()

    val fileName = "sample.txt"
    val file = File(fileName)
    ObjectOutputStream(file.outputStream()).use { out ->
        out.writeObject(person)
    }

    ObjectInputStream(file.inputStream()).use { input ->
        val p = input.readObject() as Person
        println("p = $p")
        assertEquals(p.age, person.age)
        assertEquals(p.name, person.name)
    }
}

